[package]
name = "rs-feed-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
atom_syndication = "^0.12.2"
rss = "^2.0"
chrono = "^0.4.31"

[lib]
name = "lib"
path = "lib/lib.rs"

[[bin]]
name = "aggregate"
path = "aggregate/main.rs"

